refactor: edit models
manytask/manytask pull request #200
Opened 2024-12-16 04:07 UTC by gagarinkomar

Changed lazy='dynamic' to DynamicMapped, it is the same thing but more convenient.
In Grade instead of User relationship using UserOnCourse.
Swapped TaskGroup and Task for convenience(link to course now in TaskGroup instead of Task).
Removed unused fields: is_manytask_admin, is_course_admin.
Add gitlab_instance_host field to course and validation gitlab_instance_host equal when creating UserOnCourse.
Also edited test_models.py

Current scheme:
https://drawsql.app/teams/gagarinkomar/diagrams/copy-of-copy-of-manytask

2024-12-16 19:07 UTC, feldsherov requested changes

2024-12-16 19:07 UTC, feldsherov commented on manytask/models.py
> +        return
Why do you need to swallow exception here?

You are catching exception and after that just return, this is antipattern, do we have a good reason for doing this?

2024-12-16 19:07 UTC, feldsherov commented on manytask/models.py
> +            user = session.query(User).filter_by(id=target.user_id).one()
When do we expect to have missing user in target?
Drop a comment, why can it happen?

2024-12-16 19:07 UTC, feldsherov commented on manytask/models.py
> +        if target.course:
Same question about missing course.

2024-12-19 09:39 UTC, prawwtocol commented on manytask/models.py
> +        back_populates='course')
don't we need to set up cascade options to properly handle orphaned records?
something like
`cascade="all, delete-orphan"`

2024-12-19 09:39 UTC, prawwtocol commented on manytask/models.py
> +        back_populates='course')
same question here

2024-12-19 09:40 UTC, prawwtocol commented on manytask/models.py
> +    last_submit_date: Mapped[datetime] = mapped_column(default=lambda: datetime.now(timezone.utc))
why not `func.now()`?

2024-12-19 09:49 UTC, prawwtocol commented on tests/test_models.py
> +        last_submit_date=datetime.now(timezone.utc)
to ensure consistency, create a fixture, for e.g. `current_time` and specify a fixed datetime there

2024-12-19 09:54 UTC, prawwtocol commented on tests/test_models.py
>      deadline = Deadline(data={"test_key": "test_value"})
I think we should also test invalid json and empty data

2024-12-23 15:44 UTC, gagarinkomar commented on manytask/models.py
> +        return
Because if there is a problem with finding user or course, we don't want to think about exceptions here. We swallow the exception so that sqlalchemy.orm raises the necessary exception for us when trying to create an object itself.

2024-12-23 15:51 UTC, gagarinkomar commented on manytask/models.py
> +            user = session.query(User).filter_by(id=target.user_id).one()
```
user_on_course = UserOnCourse(
    user_id=1,
    course=course,
    repo_name="user_repo"
)
```

If we create an object like this, we have user_id instead of user

2024-12-23 15:53 UTC, gagarinkomar commented on manytask/models.py
> +        if target.course:
Similar example

2024-12-23 19:44 UTC, gagarinkomar commented on manytask/models.py
> +        back_populates='course')
Added cascade options and tests for them

2024-12-23 19:45 UTC, gagarinkomar commented on manytask/models.py
> +    last_submit_date: Mapped[datetime] = mapped_column(default=lambda: datetime.now(timezone.utc))
Changed this

2024-12-23 19:48 UTC, gagarinkomar commented on tests/test_models.py
> +        last_submit_date=datetime.now(timezone.utc)
Created fixture and refactor code parts with current time usage

2024-12-23 19:49 UTC, gagarinkomar commented on tests/test_models.py
>      deadline = Deadline(data={"test_key": "test_value"})
Add test_deadline_date for test it

2024-12-25 11:49 UTC, prawwtocol commented on manytask/models.py
> +            user = session.query(User).filter_by(id=target.user_id).one()
@gagarinkomar yeah I think the point was that you were advised to include that exact comment in code -- so that anyone reading this method would understand why target.user could be None

2024-12-25 11:56 UTC, prawwtocol commented on manytask/models.py
> +        return
@gagarinkomar I think the worst part of this is catching a The Most General Exception Posssible (TM). Maybe NoResultFound would be better?

2024-12-25 15:22 UTC, akostrikov approved these changes
LGTM

2024-12-25 15:30 UTC, akostrikov commented on manytask/models.py
> +        return
@gagarinkomar can you add logging here and a todo?
Seems like a funny place to swallow errors later.

2024-12-25 15:44 UTC, akostrikov commented on manytask/models.py
> +        return
https://github.com/manytask/manytask/issues/219 added issue

2024-12-25 21:51 UTC, merged